config/routes.rb
MyAlbo::Application.routes.draw do
  resources :documents

  root :to => "documents#index"

end

app/models/document.rb
class Document < ActiveRecord::Base
  set_table_name "tt_news"
  set_inheritance_column :ruby_type
  set_primary_key "uid"

  def self.active
    where("deleted = 0 AND hidden = 0 and pid = 102")
  end
  
  def self.search(numero, documento, oggetto, descrizione, data)
    sql = "1"
    sql += " AND tx_myalbopretorio_numero=\'#{numero}\'" if !numero.nil? && !numero.blank?
    sql += " AND tx_myalbo2_documento = #{documento}" if !documento.nil? && !documento.blank?
    sql += " AND (title LIKE \'%#{oggetto}%\' OR short LIKE \'%#{oggetto}%\')" if !oggetto.nil? && !oggetto.blank?
    sql += " AND DATE_FORMAT(DATE(FROM_UNIXTIME(datetime)),'%d/%m/%Y') = '#{data}'" if !data.nil? && !data.blank?
    where(sql)
  end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  # GET /documents
  # GET /documents.xml
  def index
    @documents = Document.active.search(params[:tx_myalbopretorio_numero], params[:tx_myalbo2_documento], params[:title], params[:short], params[:data]).paginate(:page => params[:page])
    @types = [["Delibera del C.d.A.",1],["Delibera del Presidente",2],["Delibera del Direttore",3],["Decreto del Commissario Straordinario",4]]

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @documents }
    end
  end

  # GET /documents/1
  # GET /documents/1.xml
  def show
    @document = Document.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @document }
    end
  end

  # GET /documents/new
  # GET /documents/new.xml
  def new
    @document = Document.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @document }
    end
  end

  # GET /documents/1/edit
  def edit
    @document = Document.find(params[:id])
  end

  # POST /documents
  # POST /documents.xml
  def create
    @document = Document.new(params[:document])

    respond_to do |format|
      if @document.save
        format.html { redirect_to(@document, :notice => 'Document was successfully created.') }
        format.xml  { render :xml => @document, :status => :created, :location => @document }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @document.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /documents/1
  # PUT /documents/1.xml
  def update
    @document = Document.find(params[:id])

    respond_to do |format|
      if @document.update_attributes(params[:document])
        format.html { redirect_to(@document, :notice => 'Document was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @document.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.xml
  def destroy
    @document = Document.find(params[:id])
    @document.destroy

    respond_to do |format|
      format.html { redirect_to(documents_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
<%= form_for(@document) do |f| %>
  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% @document.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<h1>Editing document</h1>

<%= render 'form' %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

app/views/documents/index.html.erb
<h1>Ricerca archivio atti</h1>
<p class="bodytext">Utilizza le opzioni seguenti per ricercare all'interno dell'archivio atti.</p>
<div style="clear:both;"></div>
<%= form_tag 'http://esuverona.aitema.it:8000/documents/', :authenticity_token => false, :method => 'get', :id => "search" do %>
	<div class="ricerca"><strong>Tipo di documento</strong><br> <%= select_tag(:tx_myalbo2_documento, options_for_select(@types,params[:tx_myalbo2_documento]),:include_blank => true) %></div>
	<div class="ricerca"><strong>Numero</strong><br> <%= text_field_tag(:tx_myalbopretorio_numero) %></div>
	<div class="ricerca"><strong>Oggetto</strong><br> <%= text_field_tag(:title) %></div>
	<div class="ricerca"><strong>Data (gg/mm/aaaa)</strong><br> <%= text_field_tag(:data) %></div>
	<%= submit_tag "Avvia la ricerca", :name => nil, :class => "searchbutton" %>	
<% end %>




<% if @documents.any? %>
	<h1>Risultato</h1>
	<table class="archvio">
	  <tr>
	    <th style="text-align: left; width: 140px;">Tipo</th>
	    <th style="text-align: center; width: 30px;">nr.</th>
		<th style="text-align: center;">Data</th>
		<th>Oggetto</th>
	  </tr>
	<% @documents.each do |document| %>
	  <tr>
		<td style="width: 140px;"><strong><%= @types[document.tx_myalbo2_documento-1][0] %></strong></td>
		<td style="text-align: center;"><%= document.tx_myalbopretorio_numero %></td>
		<td style="width: 80px;text-align: center;" nowrap><%= l Time.at(document.datetime), :format => :shortdate %></td>
		<td>
			<%= link_to document.title, "http://esuverona.aitema.it/area-istituzionale/archivio-atti/atto/?tx_ttnews%5Btt_news%5D=#{document.uid}"%>
			<br>
			<%= document.short %>
		</td>
	  </tr>
	<% end %>
	</table>
<% else %>
	<h1>Risultato</h1>
	<p class="bodytext"><strong>Non è stato trovato nessun documento che soddisfa i criteri di ricerca.</strong></p>
<% end %>

<div style="clear:both;"></div>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>

app/views/documents/new.html.erb
<h1>New document</h1>

<%= render 'form' %>

<%= link_to 'Back', documents_path %>

app/views/documents/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>